services:
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: s-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    profiles: [ "flink" ]
    depends_on:
      - flink-jm
      - flink-tm

  grafana:
    image: grafana/grafana:11.6.1
    container_name: s-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    profiles: [ "flink" ]
    depends_on:
      - prometheus
