services:
  kafka:
    image: apache/kafka:3.9.0
    platform: linux/amd64
    restart: always
    ports:
      - 9092:9092
    hostname: kafka-broker-1
    container_name: s-kafka
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSITION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: INTERNAL://:9094,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9094,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "bash", "-c", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9094 --list | grep -q snowplow-enriched-good" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kafka-init:
    container_name: s-kafka-init
    image: apache/kafka:3.9.0
    platform: linux/amd64
    depends_on:
      kafka:
        condition: service_started
    entrypoint: >
      bash -c "
        echo 'echo Trying to create topics...'
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists  --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic snowplow-enriched-good
      "
    restart: on-failure

#  kafka-ui:
#    container_name: s-kafka-ui
#    image: ghcr.io/kafbat/kafka-ui:latest
#    ports:
#      - 8080:8080
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
#    depends_on:
#      - kafka

  akhq:
    image: tchiotludo/akhq
    container_name: s-kafka-akhq
    restart: unless-stopped
    ports:
      - "8085:8080"
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9094"

volumes:
  kafka_data:
