services:
  ecommerce:
    container_name: s-ecommerce
    image: node:23
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./ecommerce:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    restart: unless-stopped
